### PR TITLE
Upgrade rn version

### PR DESCRIPTION
**Pull request by betterfuture009**
I have finished React Native version upgrade and replace some npm modules

### CODE REVIEW

**Comment by arianabuilds** [comment]
@betterfuture009 I checkout out your code and tried running it. Ran into this error during npm install:
Screenshot 2023-10-07 at 4 08 14 PM

**Comment by betterfuture009** [comment]
@arianabuilds  Could you follow below steps?

rm -rf node_modules
yarn install
npx react-native run-android

If it's not working, please give me your computer connection remotely. (AnyDesk or Teamviewer).
I will try to run it on your computer remotely.

Best Regards.

**Comment by betterfuture009** [comment]
@arianabuilds  Could you check node version of your computer ?
node --version

It need to use node 18 surely.
If you are using node 18, you can follow below steps.

1) Please remove "node_modules" and "yarn.lock" surely.
2) yarn install
3) cd android
4) ./gradlew clean
5) cd ..
6) npx react-native run-android

**Comment by arianabuilds** [comment]
@betterfuture009 I followed your steps and here's where I got stuck. Also, can you send me another updated APK to share and see if it works for Android 13? The one you sent perviously sadly didn't work. 

Screenshot 2023-10-09 at 9 14 34 PM

**Comment by betterfuture009** [comment]
Screenshot 2023-10-10 at 4 16 09 PM

Screenshot 2023-10-10 at 4 18 24 PM

Could you remove current JDK version and install JDK 11? I am using JDK 11 and run it.

**Comment by betterfuture009** [comment]
@arianabuilds 

Also this is the APK (release). I have tested with two android devices and it's working as well.
https://drive.google.com/file/d/1-X27Yyjr0Uu0k-3ZCBinKeg1Slczg_5G/view?usp=sharing

**Comment by arianabuilds** [comment]
@betterfuture009 We were able to install the APK of the latest version. However, I see 200 or more files were changed/deleted — why? And because of that the CSS is now broken. :(  See attached screenshots:

**Comment by betterfuture009** [comment]
@arianabuilds  

I can't use original source code because it's very old version. (react native version)
So I have created new project with latest react native version and copy & paste original code one by one.

To support recent iOS & Android version, we need to follow.

For CSS issue, could you give me correct UI screen together? Let me compare and adjust them.

Best Regards.

**Pull request closed without merging**
